language: node_js

node_js:
  - "lts/*"

before_deploy:
  - "echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc"
  - "echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' > .npmrc"

deploy:
  # Publish to https://registry.npmjs.org/
  - provider: script
    script: "npm publish --registry=https://registry.npmjs.org/"
    skip_cleanup: true
    on:
      branch: master
      tags: true

  # Publish to https://npm.pkg.github.com/
  - provider: script
    script: "npm publish --registry=https://npm.pkg.github.com/"
    skip_cleanup: true
    on:
      branch: master
      tags: true

env:
  - secure: "am/TZlMyozJeAadnXoKNfIap7KEBHxkYGYSarwovRd3AKXoe0IGj9DqdOrU1QFE5jx9IhL6OcVjjhVkyIrPBa8gTFon3BWXNhu/yzw/NvzlAQ5ezo9RDHp6Sga2GYjbxQlBJ+92jzgLp82muDqerATjc51OoGVHKH/C7zaaVPBv77czGDkktp2O/17Dh2jXsIXKTCz4QGvwo1HjsypIe/LikY/NAWzLR4MOwlsy04yOKXB+17RLVxxBoWDMSqWuHqeU/zxfANas3pU1JPJuTraDS+h/BQb198/HgCxXJwisihM/QOnMC/YMPcXv17oqRuFAmLQGshN84ogeUZCo6qo6nqgYtUVyA10q6Zpt4a87iCb2cXeruOS++aO4mXbX5XIzq3lU/iN9GsT90y6oCEdilxKIeV9wReE/dB3RMKmAPSAUaGy/hsUjEioq+qN+sy2KGFebhYqVjH5zDERtuWbg3HdQiauH5uqxyysQ9QIyttAVnSH4sxk5brsQVXfyqez/8x2dcCfTWB5qIzNo6uMPDUlLPTyiFynF25cV0U1eZekLp8Rvyl+IaGkL4WCwcykt+yewU6j9uFFxMTaiBgUbpQigJaQVXFhW4AexNsNyMvQfaqujMod2N3FqGOpWQrxAcAL+a/FgSLbmrioTEAW8e3TnoGmbnuY9ODLMReOo="
  - secure: "SOFa6sncC6GYjPrOYbYCQPThviRG5suPLcbiqMTXyT2JRWJsnFCcNhrSzs94fNvGG4fghe8B4+iRTW2UmKb9Y5d1/WFmBywQXSiPgJXUt047gcQYoHY7lrnsIFV/+qf3kpVh+xaT5xJvI1Nz3WxuL1F6F5p+inhA5Tk6E6a7pHCUFCe7pUFzl3cFbjGKbot6rwPzhUGSscmXFDYSsNUHalUWAfrTDk3ourzcEJAiPIV9sN8He6Pvo34mHR5WKPmlY6Jer05SVoGdbr1goIlVXYmULELQW/qkM/H9lkOIC1ty4uTMA2S4rPgOZUvrvanMaX5B6nFVN9EedhqBrNeOsHhbR40mWlTEvBssVspOmx8zuqmj+I+EcIvzXQRaqqVcpfesocJZmcrOhAnPFiuvsE5wGldiwF6emmLCul2Y9i9Zczb/Hz9zOwMIA4hImz1G7EMmx5keAIOs+13eWJ1Ge0TRPrXn6C4+zSBTGJ5UC4Jdp/d+4z8LzlUqAc3c4deo8HDxuTU1KATeh8C+phEW3bRzuSepLl9kpc6Soy0oDY94vmsR9p6CY/VrUzmTorT6JZU/T5YotvCC1Y65l3sgigX04bisjzACZ9OnLqiYZbwDUBPP+4sppg7MhKGeAKxq1lm/jXsp4asF1mawSicq59Qk/UCO7kuorh1cYPY0Siw="
