language: node_js

node_js:
  - "lts/*"

before_deploy:
  - "echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc"
  - "echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' > .npmrc"

deploy:
  # Publish to https://registry.npmjs.org/
  - provider: script
    script: "npm publish --registry=https://registry.npmjs.org/"
    skip_cleanup: true
    on:
      branch: master
      tags: true

  # Publish to https://npm.pkg.github.com/
  - provider: script
    script: "npm publish --registry=https://npm.pkg.github.com/"
    skip_cleanup: true
    on:
      branch: master
      tags: true

env:
  global:
    - secure: So2NXjSG3OBVLMEmtQIht7P+06QtdcUSDEEABOjOseRYZhdaOeYHYEKAAff/wbbe/nmKH52Ppilfw60U5xbXpItI0TZGOst2tAZUZ5X/OZZtMaMrioAD3rhmdkvSAZlaeMmjYXRRKMN/4083j15nsI7OQMBaA6M0l+3aYyB/HgPf+5H57RA8R0slru+l0p3+orrutsR9GyOAXgul3CfzGINt+Wq6QKyNft3pe2+q8IbqXPzT19nVXJbRg1GhX492JVlqJOeA1y1BEzHLKflof0k8vq9Zm2BVhWbqHoHC1nLPn9dlElfF+iLYJlfdAPKjBf3WOrwsm0k2BKGV95voiWKDZvrOfIyJTdWTRo/Y0w8gc47n8VRUKXY+mbRrdocu2kO/1LmblxZCqF2+4MwPXVrtSODASGrobtH1Zc8fbCIefGtlxvD8QL4e+r2k4NmpU70ZEa/OWzMYEJQMVIiNv5B8ewbmpNJ4Titp/VkJouHg9jfJ8quiQMNSdSjnOF9IiCoDHs/qmFgBhoilI8sAkYHhijxV8fJjl19yfJARFLkrqMHLK2RkNwEw6DYW646OhRwznzMpQi+YOhbHIYTKOUkMMM3pFB6oUPz/hY6ABg8UhnKGEClCSA8VbnXdnv0RXnFnaq5DjsbRqp9sFQBdYy8vTw5d/T3Mx02WuHLUvLs=
