language: node_js

node_js:
  - "lts/*"

before_deploy:
  - "echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc"
  - "echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' > .npmrc"

deploy:
  # Publish to https://registry.npmjs.org/
  - provider: script
    script: "npm publish --registry=https://registry.npmjs.org/"
    skip_cleanup: true
    on:
      branch: master
      tags: true

  # Publish to https://npm.pkg.github.com/"
  - provider: script
    script: "npm publish --registry=https://npm.pkg.github.com/"
    skip_cleanup: true
    on:
      branch: master
      tags: true

env:
  - secure: EveczrD1FyEvYzq9qSJIVggwxGwGy0Gp9al+yZD+LOjVl1CfYZMiqKbwPhdiRPmq9ZKk135fYMSva/mtpYriwKBcwmvEeQfd003CviTK7Osetj+67wPBSv1E9LO6zaxqB7/EnVdZMb7H26h3yCNkaHWueNjHu86WoEGbZzdwjrzgK+eSlqMppY9LlQRRB1WKZ+mZFS1P79ReT/4ecUVrbUgvGFF81ssTkO7xqTYQwnqKJK0ywbu+VmSzkeXWRaGkPNLqolS0qJUuCsZlmMB1lWMP9/p0WjJnmJDOB3/gGtb4pf1VP/AYni9phaTfgqn9E8kl6i/kdrXu2gNoHv4k2OSdAvE2UtfuQZeU2s7geY75H1nmLF8pni14QFtl1PnLTq3xG1LdF7QIwFFdUuGAdqz0yMXVQ/CdYw6k1j4467jjCQNBe9zuBT0FBTC4z5pFcSSRbF2J9iIs6hDxrKCtmr0tJNBNYHaibP6rZY9zqguMyOV3+sEGiejKGhFd+nEZrCw8W97NVSxD5jWwShdmZMhv66JpLCBnNt1aML/BXTB1SHIXzmVWpQH3gAjUYfyI5nYKIts3vrWdFe5Q+/kcKrjKOOUPqa4T2mM/gCuOn5bghEf7jt/QYkbjL98il7r8Hv7zt1zZJFDygkfQb7n7yL0XDSmxzFbHrqilcmhb9N0=
